spring:
  application:
    name: backend_empleado
  datasource:
    url: jdbc:postgresql://localhost:5432/db_taller
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create  # cambiar a "update" cuando haya datos que conservar
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082
  error:
    include-message: always
